config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show]
  delete 'users/:id/delete_all', to: 'users#delete_all', as: 'user_delete_all'
  resources :news, only: [ :show, :destroy, :index ]

  resources :projects, only: [ :index, :show ] do
    resources :news, only: [ :new, :create ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :project, foreign_key: "project_id"
  validates :author, :project, :title, :description, presence: true
  validates :title, uniqueness: { scope: [ :author, :project ], message: "news exists already" }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :news
end

app/models/user.rb
class User < ApplicationRecord
  has_many :news, foreign_key: "author_id"

  def to_label
    login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    case params[:order]
      when 'alphabetical' then @news = News.order(title: :desc)
      when 'oldest_first' then @news = News.order(created_on: :desc)
      else @news = News.order(created_on: :asc)
    end
  end

  def show
    @news = News.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    @project = Project.find(params[:project_id])
    @news.project = @project

    if @news.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def destroy
    @news = News.find(params[:id])
    project = @news.project
    @news.destroy
    redirect_to project_path(project)
  end

  private

  def news_params
    params.require(:news).permit(:title, :summary, :description, :author_id)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @news = @project.news
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @news = @user.news
  end

  def delete_all
    @user = User.find(params[:id])
    @news = @user.news
    @news.destroy_all
    redirect_to user_path(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/_form.html.erb
<%= simple_form_for @news, url: project_news_index_path  do |f| %>
  <%= f.input :title %>
  <%= f.input :summary %>
  <%= f.input :description %>
  <%= f.association :author %>
  <%= f.button :submit %>
<% end %>

app/views/news/_news.html.erb
<h3><%= link_to news.title, news_path(news) %></h3>
<p><%= news.summary %></p>
<p><%= news.description %></p>
<p>Author: <%= link_to news.author.firstname %></p>
<p>Project: <%= link_to news.project.name, project_path(news.project) %></p>

app/views/news/index.html.erb
<h1>All news</h1>
<%= render partial: 'news', collection: @news %>

app/views/news/new.html.erb
<%= render partial: 'form' %>

app/views/news/show.html.erb
<%= render partial: 'news', locals: { news: @news } %>
<%= button_to "Delete", news_path(@news), method: 'delete' %>

app/views/projects/_project.html.erb
<h3><%= link_to project.name, project_path(project) %></h3>
<p class="description"><%= project.description %></p>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<%= render partial: 'project', collection: @projects %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<%= button_to "Create new news entry", new_project_news_path(@project), method: 'get' %>
<%= render partial: 'news/news', collection: @news %>

app/views/users/show.html.erb
<h1><%= @user.login %></h1>
<p><%= @user.firstname %></p>
<p><%= @user.lastname %></p>

<%= render partial: 'news/news', collection: @news %>

<%= button_to "Delete all news", user_delete_all_path, method: 'delete' %>